Docker-compose.yml

version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: chatapp_db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
